### ISSUE TITLE
Advanced Edition Update TODO List

### ISSUE THREAD

**Issue by KnightMiner** [itb-community/ITB-ModLoader#130]
Will add more tasks here as we discover things that are broken.

* [x] Update Hangar GUIs
* [ ] Fix hangar GUIs when a squad replaces secret squad
* [x] Test weapon deck
* [x] It is possible something in the update broke FURL. Verify if this is the case and consider whether backwards compat is in order
* [x] Determine why no vek eggs spawn on vek egg missions
* [x] Remove custom difficulty
* [x] Possible regression: `GetCurrentMission()` returns `nil` until the player mechs are movable on the first turn
* [ ] Achievement squad victory ribbons for unfair mode
* [ ] Fix display of achievements when replacing secret squad

Nice features made possible by Advanced Edition
* [ ] Mod loader UI for injecting extra mechs into custom squads

**Comment by KnightMiner** [comment]
Regarding the weapon deck, there are now 2 lists in the deck: `WeaponDeck` and `PodWeaponDeck`. Both are populated from sepaarate lists, so we should support setting weapons to either in the weapon deck selector.

Also consider that the lists are populated ffrom two local fields each: one for regular weapons and one for AE weapons.

Suggested approach: give each weapon two toggles:
* Weapon Deck: disabled, enabled, enabled (AE only)
* Time Pods/Perfect Island: disabled, enabled, enabled (AE only)

**Comment by KnightMiner** [comment]
Fixed most hangar UI bugs, only remaining ones are when replacing the secret squad.

Bug 1: the metals overlap, we need to draw a rectangle probably:
![image](https://user-images.githubusercontent.com/12155288/180335555-f17aefe3-e86c-4838-8146-2e37535d8405.png)

Bug 2: achievements overlap the "no achievements" background, also need to draw a rectangle to fix

![image](https://user-images.githubusercontent.com/12155288/180335631-b9abc25e-aced-4e96-b809-5bb36bb83111.png)

Bug 3: achievements have no tooltips. Need to add our own.

**Comment by KnightMiner** [comment]
Since we are past the initial pre-release, going to split out the remaining tasks into their own issues for easier tracking.

**Comment by KnightMiner** [comment]
This issue is superceeded by the linked issues.
